### ISSUE TITLE
Duplicated layer names resulting in conversion faliure

### ISSUE THREAD

**Issue by cillia1** [LobsterFestival/Live2D-CSV-Converter#1]
If there's multiple layers with the same name, the converter doesn't alter the artmesh IDs correctly to avoid conflict, resulting in the corrected CSV not being able to import (if one thing is conflicting then the whole thing fails).

Pre-converted:
GUID,Types,ID,Name,Label color
7f400c59-c931-4b9e-b40a-7f566b0a14b1,ARTMESH,ArtMesh287,Layer 2 2,UNDEFINED:#00000000
3f7470bd-da83-4043-ad5e-a6e9ea8e216f,ARTMESH,ArtMesh288,Layer 2 2,UNDEFINED:#00000000
558840c5-a2c9-4193-81d4-5ad26a0bcfe9,ARTMESH,ArtMesh289,Layer 2 2,UNDEFINED:#00000000
b30b6bc7-c1a1-4cf6-9c9d-e92e459b2bc5,ARTMESH,ArtMesh290,angle fill,UNDEFINED:#00000000
69907714-cb96-49c1-b222-405d71ed5fba,ARTMESH,ArtMesh291,angle fill,UNDEFINED:#00000000
e898e412-9c17-4310-94cc-ac596beecb75,ARTMESH,ArtMesh292,angle fill,UNDEFINED:#00000000

Post-converted:
GUID,Types,ID,Name,Label color
7f400c59-c931-4b9e-b40a-7f566b0a14b1,ARTMESH,Layer_2_2,Layer 2 2,UNDEFINED:#00000000
3f7470bd-da83-4043-ad5e-a6e9ea8e216f,ARTMESH,Layer_2_22,Layer 2 2,UNDEFINED:#00000000
558840c5-a2c9-4193-81d4-5ad26a0bcfe9,ARTMESH,Layer_2_22,Layer 2 2,UNDEFINED:#00000000
b30b6bc7-c1a1-4cf6-9c9d-e92e459b2bc5,ARTMESH,angle_fill,angle fill,UNDEFINED:#00000000
69907714-cb96-49c1-b222-405d71ed5fba,ARTMESH,angle_fill2,angle fill,UNDEFINED:#00000000
e898e412-9c17-4310-94cc-ac596beecb75,ARTMESH,angle_fill2,angle fill,UNDEFINED:#00000000

**Comment by LobsterFestival** [comment]
*Worked with Cillia on debugging this outside of Github*
Solution, Duplicated Names (like Layer 2 2 or angle fill in example posted) freak live2D out when imported with not their original ArtMeshX format. Why, I couldn't tell you. The solution is to adhere to best practices and NOT have duplicated names as they are ambiguous. Once duplicated names for artmeshes were changed, the export/conversion/import process works as intended.
