### ISSUE TITLE
Encoding and TypeError

### ISSUE THREAD

**Issue by rhubarbc** [LobsterFestival/Live2D-CSV-Converter#2]
Tried using latest versions of Python and pandas. 
Tried using earlier versions (sep'23 compatible) versions. 
Both give same output errors.

```
Traceback (most recent call last):
  File "C:\Users\name\live2d\live2d_CSV_cleaner.py", line 158, in <module>
    main()
  File "C:\Users\name\live2d\live2d_CSV_cleaner.py", line 154, in main
    df.to_csv(filename, encoding='utf-8', index=False, line_terminator='\n')
TypeError: NDFrame.to_csv() got an unexpected keyword argument 'line_terminator'
```

Python and libraries are fresh installs.

**Comment by LobsterFestival** [comment]
Thank you for bringing this up, It is now corrected on the main branch, looks like as part of pandas updating, they changed the function signature of to_csv() to align with their other functions. the argument line_terminator became 'lineterminator' 
Corrected and pushed to main branch.
